### ISSUE TITLE
Inference using unlabeled data

### ISSUE THREAD

**Issue by gruossomonica** [Andreas-Pfeuffer/LSTM-ICNet#3]
Hi,
Thank you for your work. It's really interesting! I have some questions. Can I test your pretrained models using unlabeled images/videos? Can I run your code on Windows? At the moment, I don't have Ubuntu already installed on my computer.
I look forward to your reply.

Best regards,

Monica Gruosso

**Comment by Andreas-Pfeuffer** [comment]
Thank you :)

1) Yes, you can use my inference script for unlabeled data. However, you must create a virtual label for each image, e.g. it could be a simple segmentation map only containing zeros. Furthermore, you must create a corresponding txt-file, where each line consist of the following data:
<path2image/video> <path2DummyLabel> 
Furthermore, you have to modify the pathes in src/datasets/*

2) I provide a virtual environment in this repo (singularity container). Look at the follwoing link, how to install singularity on windows: https://sylabs.io/guides/3.0/user-guide/installation.html

I hope that I could help you!

**Comment by gruossomonica** [comment]
Thank you very much @Andreas-Pfeuffer! I will try asap.

Best regards,

Monica Gruosso
